#!/bin/bash
#==================================================================================================
#=
#=                            filename:autouseradd
#=                              author:WangXinkun
#=                             created:25/06/2019
#=
#==================================================================================================
echo "=======================Oo欢迎使用阿坤脚本,祝您使用愉快oO======================="&&sh sky.sh
while :

do
read -p "请输入您想要的用户名:" i
if [ "$i" = ""  ];then
           echo "用户不能为空！"
     
elif [ -e /home/$i ];then
           echo "用户已存在！！"     
else
           break           

fi
done

     useradd -m $i
read -p "请您输入$i 用户密码:" $2
if [ $2 -z   ];then
           echo "123" | passwd --stdin $i> /dev/null 2>&1
     chage -d 0 $i
else
           echo "$2" | passwd --stdin $i
fi


echo "                       --------成功创建用户$i！--------           "
echo "           ===================期待您的再次使用！！===================          "  

